server:
  port: 8080
spring:
  application:
    name: WTET_backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.72.204:3306/wtet
    username: wtet
    password: fKBnhZ8P8KiBxfek
    hikari:
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 5
      maximum-pool-size: 15
      allow-pool-suspension: false
  main:
    allow-bean-definition-overriding: true